import { useTranslation } from "next-i18next";
import urljoin from "url-join";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { requiredNamespaces } from "@/config/i18n";
import Link from "next/link";
import { GetStaticProps } from "next";
// import { GetServerSideProps } from "next";
import { TextBlock } from "@/about/components";
import Head from "next/head";
import { atomicClassNames } from "@/utils";
import {
  Box,
  FooterContainer,
  GridContainer,
  Header,
  Hidden,
} from "@/shared/components";
import { IMeta, Meta } from "@/shared/layouts/components";

const About = () => {
  const { t } = useTranslation();

  const metaData: IMeta = {
    title: t("app:about:title"),
    description: "About me info",
    url: urljoin("http://localhost:3000/", "about"),
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Meta {...metaData} />

      <Box
        className={atomicClassNames({ display: "flex" })}
        css={{ flexDirection: "column", minHeight: "100vh" }}
      >
        <Header>
          <Hidden below="md">123</Hidden>
          <Hidden above="md">456</Hidden>
        </Header>

        <GridContainer fullBleed={{ "@initial": true, "@md": false }}>
          <TextBlock />
          <div>{t("app:about:title")}</div>
          <div>ABOUT PAGE</div>
          <Link href={"/"} passHref>
            Home
          </Link>
        </GridContainer>

        <Box css={{ marginTop: "auto" }}>
          <FooterContainer />
        </Box>
      </Box>
    </>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale = "en" }) => ({
  props: {
    ...(await serverSideTranslations(locale, requiredNamespaces)),
  },
});

// export const getServerSideProps: GetServerSideProps = async ({ locale = "en" }) => ({
//   props: {
//     ...(await serverSideTranslations(locale, requiredNamespaces)),
//   },
// });

export default About;
